# Generated by Django 4.1.3 on 2023-01-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('duracion', models.CharField(max_length=15)),
                ('maestro', models.CharField(max_length=30)),
                ('condition', models.CharField(choices=[('aquatica', 'aquatica'), ('no aquatica', 'no aquatica')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
